server:
  port: 9091
  tomcat:
    max-connections: 300
    uri-encoding: UTF-8
    max-http-form-post-size: 0

spring:
  application:
    name: crawler
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      filter: stat
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: site.vloving.blog.bean.PO

eureka:
  instance:
    instance-id: myServer-crawler:9091
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka/
